name: Hola Mundo
run-name: Example de Github Actions
on: [push]
jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps: #Lista de steps del job hola-mundo
      - name: Public IP #Nombre del step
        id: ip #identificador usable dentro del job para otros steps
        uses: haythem/public-ip@v1.3 #Usará el action haythem/public-ip
      - name: Hola mundo #Segundo step de nombre Hola mundo
        run: echo ¡Hola Mundo desde ${{ steps.ip.outputs.ipv4 }}! #bash
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Run index
        run: node index.js